name: Products

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: products
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
        
      - name: Install deps
        run: install ci
      - name: Run tests
        run: npm test
